version: 2
jobs:
  build:
    docker:
      - image: thewtex/centos-build:latest

    working_directory: /usr/src/ITKTextureFeatures

    steps:
      - checkout

      - run:
          name: build
          command: ./createPythonWheels.sh

      - store_artifacts:
          path: /usr/src/ITKTextureFeatures/dist/
          destination: 
